version: "3.3"
services:
  database:
    image: "questdb/questdb"
    container_name: "maro_vis_questdb"
    ports:
      - "9000:9000" # REST API, web console
      - "8812:8812" # Postgres
      - "9009:9009" # influxdb line protocol
    volumes:
      - ./data:/root/.questdb/db
    # override configuration via environemnt variables
    # https://questdb.io/docs/reference/configuration#environment-variables
    environment: 
      QDB_TELEMETRY_ENABLED: "false" # disable telemetry collecting
      QDB_HTTP_WORKER_COUNT: 4 # 4 private worker thread
    #   QDB_HTTP_SECURITY_READONLY: "true" # disable writing interface for web console
    #   QDB_PG_USER : admin
    #   QDB_PG_PASSWORD : quest
  fileserver:
    image: "nginx:1.19.6-alpine"
    ports:
      - "9103:9103"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  # enable web server
  # web:
  #   build: .
  #   ports:
  #     - "9988:9988"
  #   volumes: 
  #     - ./web:/maro_vis

