container_usage_proportion:
  period: 112
  sample_nodes:
  - - 0
    - 0.018000000000000002
  - - 1
    - 0.018003146369964366
  - - 2
    - 0.018012575580213516
  - - 3
    - 0.018028257962963527
  - - 4
    - 0.018050144175636353
  - - 5
    - 0.0180781653561098
  - - 6
    - 0.018112233339383266
  - - 7
    - 0.018152240934977425
  - - 8
    - 0.018198062264195163
  - - 9
    - 0.018249553156182492
  - - 10
    - 0.01830655160154343
  - - 11
    - 0.01836887826208148
  - - 12
    - 0.018436337035063942
  - - 13
    - 0.01850871567023367
  - - 14
    - 0.018585786437626907
  - - 15
    - 0.018667306844095993
  - - 16
    - 0.018753020396282533
  - - 17
    - 0.01884265740764039
  - - 18
    - 0.01893593584696933
  - - 19
    - 0.019032562225789522
  - - 20
    - 0.019132232521764884
  - - 21
    - 0.01923463313526982
  - - 22
    - 0.019339441876089665
  - - 23
    - 0.0194463289771503
  - - 24
    - 0.019554958132087373
  - - 25
    - 0.019664987553390526
  - - 26
    - 0.019776071047793383
  - - 27
    - 0.019887859105525617
  - - 28
    - 0.02
  - - 29
    - 0.020112140894474384
  - - 30
    - 0.020223928952206614
  - - 31
    - 0.020335012446609475
  - - 32
    - 0.020445041867912628
  - - 33
    - 0.0205536710228497
  - - 34
    - 0.020660558123910332
  - - 35
    - 0.02076536686473018
  - - 36
    - 0.020867767478235117
  - - 37
    - 0.02096743777421048
  - - 38
    - 0.021064064153030672
  - - 39
    - 0.021157342592359612
  - - 40
    - 0.021246979603717468
  - - 41
    - 0.021332693155904008
  - - 42
    - 0.021414213562373094
  - - 43
    - 0.02149128432976633
  - - 44
    - 0.02156366296493606
  - - 45
    - 0.02163112173791852
  - - 46
    - 0.02169344839845657
  - - 47
    - 0.02175044684381751
  - - 48
    - 0.021801937735804838
  - - 49
    - 0.021847759065022575
  - - 50
    - 0.021887766660616734
  - - 51
    - 0.0219218346438902
  - - 52
    - 0.021949855824363648
  - - 53
    - 0.021971742037036474
  - - 54
    - 0.021987424419786485
  - - 55
    - 0.021996853630035635
  - - 56
    - 0.022
  - - 57
    - 0.021996853630035635
  - - 58
    - 0.021987424419786485
  - - 59
    - 0.021971742037036474
  - - 60
    - 0.021949855824363648
  - - 61
    - 0.0219218346438902
  - - 62
    - 0.021887766660616734
  - - 63
    - 0.021847759065022575
  - - 64
    - 0.021801937735804838
  - - 65
    - 0.02175044684381751
  - - 66
    - 0.02169344839845657
  - - 67
    - 0.02163112173791852
  - - 68
    - 0.02156366296493606
  - - 69
    - 0.02149128432976633
  - - 70
    - 0.021414213562373097
  - - 71
    - 0.021332693155904008
  - - 72
    - 0.021246979603717468
  - - 73
    - 0.021157342592359612
  - - 74
    - 0.021064064153030675
  - - 75
    - 0.020967437774210482
  - - 76
    - 0.020867767478235117
  - - 77
    - 0.02076536686473018
  - - 78
    - 0.020660558123910336
  - - 79
    - 0.0205536710228497
  - - 80
    - 0.02044504186791263
  - - 81
    - 0.020335012446609475
  - - 82
    - 0.020223928952206618
  - - 83
    - 0.020112140894474384
  - - 84
    - 0.02
  - - 85
    - 0.019887859105525617
  - - 86
    - 0.019776071047793387
  - - 87
    - 0.019664987553390526
  - - 88
    - 0.019554958132087373
  - - 89
    - 0.019446328977150304
  - - 90
    - 0.019339441876089665
  - - 91
    - 0.01923463313526982
  - - 92
    - 0.019132232521764884
  - - 93
    - 0.019032562225789522
  - - 94
    - 0.01893593584696933
  - - 95
    - 0.01884265740764039
  - - 96
    - 0.018753020396282533
  - - 97
    - 0.018667306844095993
  - - 98
    - 0.018585786437626907
  - - 99
    - 0.01850871567023367
  - - 100
    - 0.018436337035063942
  - - 101
    - 0.01836887826208148
  - - 102
    - 0.018306551601543434
  - - 103
    - 0.018249553156182492
  - - 104
    - 0.018198062264195163
  - - 105
    - 0.01815224093497743
  - - 106
    - 0.018112233339383266
  - - 107
    - 0.0180781653561098
  - - 108
    - 0.018050144175636353
  - - 109
    - 0.018028257962963527
  - - 110
    - 0.018012575580213516
  - - 111
    - 0.018003146369964366
  sample_noise: 0.001
container_volumes:
- 1
order_generate_mode: fixed
ports:
  demand_port_001:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.2
    order_distribution:
      source:
        noise: 0.03599359535144951
        proportion: 0.25
      targets:
        transfer_port_001:
          noise: 0.08049795913094565
          proportion: 1
  demand_port_002:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.2
    order_distribution:
      source:
        noise: 0.028165770016070624
        proportion: 0.25
      targets:
        transfer_port_001:
          noise: 0.06286664753177106
          proportion: 1
  supply_port_001:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.2
    order_distribution:
      source:
        noise: 0.0
        proportion: 0
  supply_port_002:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.2
    order_distribution:
      source:
        noise: 0.0
        proportion: 0
  transfer_port_001:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.2
    order_distribution:
      source:
        noise: 0.03930003216584521
        proportion: 0.5
      targets:
        supply_port_001:
          noise: 0.07702248660047659
          proportion: 0.5
        supply_port_002:
          noise: 0.011279220529908651
          proportion: 0.5
routes:
  route_001:
  - distance: 60
    port_name: transfer_port_001
  - distance: 60
    port_name: supply_port_001
  - distance: 60
    port_name: supply_port_002
  route_002:
  - distance: 60
    port_name: transfer_port_001
  - distance: 60
    port_name: demand_port_001
  - distance: 60
    port_name: demand_port_002
stop_number:
- 4
- 3
total_containers: 100000
vessels:
  rt1_vessel_001:
    capacity: 8000
    parking:
      duration: 1
      noise: 1
    route:
      initial_port_name: transfer_port_001
      route_name: route_001
    sailing:
      noise: 2
      speed: 20
  rt1_vessel_002:
    capacity: 9000
    parking:
      duration: 1
      noise: 1
    route:
      initial_port_name: supply_port_001
      route_name: route_001
    sailing:
      noise: 2
      speed: 10
  rt1_vessel_003:
    capacity: 10000
    parking:
      duration: 1
      noise: 1
    route:
      initial_port_name: supply_port_002
      route_name: route_001
    sailing:
      noise: 2
      speed: 6
  rt2_vessel_001:
    capacity: 8000
    parking:
      duration: 1
      noise: 1
    route:
      initial_port_name: transfer_port_001
      route_name: route_002
    sailing:
      noise: 1
      speed: 20
  rt2_vessel_002:
    capacity: 9000
    parking:
      duration: 1
      noise: 1
    route:
      initial_port_name: demand_port_001
      route_name: route_002
    sailing:
      noise: 1
      speed: 10
  rt2_vessel_003:
    capacity: 10000
    parking:
      duration: 1
      noise: 1
    route:
      initial_port_name: demand_port_002
      route_name: route_002
    sailing:
      noise: 2
      speed: 6
