# this is the tick=0 for all the sub-engines
# stock/futures whoes beginning date later than this, will be filled with 0
beginning_date: "2019-01-01"
time_zone: "Asia/Shanghai"
account:
  money: 10000 # 1 unit

type: stock # Stock, futures.
data_path: "./"
stocks: # Stocks to simulate.
  - "000001"
  - "000002"

order_mode:
  - "market_order"
  - "limit_order"
  - "stop_order"
  - "stop_limit_order"

trade_constraint:
  min_buy_unit: 100
  min_sell_unit: 100
  deal_price: "opening_price"  # Options: opening_price, closing_price, highest_price, lowest_price, adj_closing_price. Use the specified price as deal_price
  slippage: 0.00246  # Slippage config, buy price shall be (1+slippage/2)*deal_price, sell price shall be (1-slippage/2)*deal_price.
  close_tax: 0.001  # Close tax, shell charge close_tax*sell_price when selling out.
  commission: 0.0003  # Commission, shell charge commission*sell_price or commission*buy_price when trading.
  allow_split: true  # If allow auto split the order when trading amount greater than split_trade_percent of the market trading volume.
  allow_day_trade: false  # If allow the day trade.
  max_trade_percent: 0.2  # Max trading percent for stocks.
  split_trade_percent: 0.000001  # Max trading percent for 1 split trade.
