# Initial buffer time budget.
BUFFER_TIME_BUDGET: 0
# The number of ticks to delay when agent decides not to assign VM.
DELAY_DURATION: 1

# Path of the vm table data.
VM_TABLE: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vmtable.bin"

# Path of the cpu readings file.
CPU_READINGS: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vm_cpu_readings-file-1-of-195.bin"

PROCESSED_DATA_URL: "https://marodatasource.blob.core.windows.net/vm-scheduling-azure/azure.2019.10k/azure.2019.10k.tar.gz"

# True means kill all VMs on the overload PM.
# False means only count these VMs as failed allocation, but not kill them.
KILL_ALL_VMS_IF_OVERLOAD: True

# Oversubscription configuration.
# Max CPU oversubscription rate.
MAX_CPU_OVERSUBSCRIPTION_RATE: 1.15
# Max memory oversubscription rate.
MAX_MEM_OVERSUBSCRIPTION_RATE: 1
# Max CPU utilization rate.
MAX_UTILIZATION_RATE: 1

PM:
  SKU:
    TYPE_1:
      TYPE_NAME: 1
      AMOUNT: 100
  # CPU cores of each PM.
  CPU: 16
  # The unit of the memory is GB.
  MEMORY: 128
  # GPU: 4
