# Initial buffer time budget.
BUFFER_TIME_BUDGET: 0
# The number of ticks to delay when agent decides not to assign VM.
DELAY_DURATION: 1

# Path of the vm table data.
VM_TABLE: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vmtable.bin"

# Path of the cpu readings file.
CPU_READINGS: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vm_cpu_readings-file-1-of-195.bin"

PROCESSED_DATA_URL: "https://marodatasource.blob.core.windows.net/vm-scheduling-azure/azure.2019.10k/azure.2019.10k.tar.gz"

# 1 means kill all VMs on the overload PM.
# 0 means only count these VMs as failed allocation, but not kill them.
KILL_ALL_VMS_IF_OVERLOAD: 1

# Oversubscription configuration.
# Max CPU oversubscription rate.
MAX_CPU_OVERSUBSCRIPTION_RATE: 1.15
# Max memory oversubscription rate.
MAX_MEM_OVERSUBSCRIPTION_RATE: 1
# Max CPU utilization rate.
MAX_UTILIZATION_RATE: 1
# The amount of the PM.
PM_AMOUNT: 100

PM:
  # CPU cores of each PM.
  CPU: 16
  # The unit of the memory is GB.
  MEMORY: 128
  # GPU: 4
  # NOTE: Energy consumption parameters should refer to more research.
  POWER_CURVE:
    # The calibration parameter used for the CPU utilization vs energy consumption model.
    CALIBRATION_PARAMETER: 1.4
    # The idle power usage of a machine.
    BUSY_POWER: 10
    # The busy power usage of a machine.
    IDLE_POWER: 1
