# Initial buffer time budget.
BUFFER_TIME_BUDGET: 0
# The number of ticks to delay when agent decides not to assign VM.
DELAY_DURATION: 1

# Path of the vm table data.
VM_TABLE: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vmtable.bin"

# Path of the cpu readings file.
CPU_READINGS: "~/.maro/data/vm_scheduling/.build/azure.2019.10k/vm_cpu_readings-file-1-of-195.bin"

PROCESSED_DATA_URL: "https://marodatasource.blob.core.windows.net/vm-scheduling-azure/azure.2019.10k/azure.2019.10k.tar.gz"

# Oversubscription configuration. The unit of both rates are percentages.
MAX_OVERSUB_RATE: 15
MAX_UTILIZATION_RATE: 100

PM:
  AMOUNT: 100
  CPU: 32
  # The unit of the memory is GB.
  MEMORY: 128
  # GPU: 4
  # NOTE: Energy consumption parameters should refer to more research.
  POWER_CURVE:
    # The calibration parameter used for the CPU utilization vs energy consumption model.
    CALIBRATION_PARAMETER: 1.4
    # The idle power usage of a machine.
    BUSY_POWER: 10
    # The busy power usage of a machine.
    IDLE_POWER: 1
