container_usage_proportion:
  period: 112
  sample_nodes:
  - - 0
    - 0.007
  - - 1
    - 0.007001573184982184
  - - 2
    - 0.007006287790106758
  - - 3
    - 0.0070141289814817645
  - - 4
    - 0.007025072087818177
  - - 5
    - 0.007039082678054901
  - - 6
    - 0.007056116669691632
  - - 7
    - 0.0070761204674887135
  - - 8
    - 0.007099031132097581
  - - 9
    - 0.007124776578091246
  - - 10
    - 0.007153275800771716
  - - 11
    - 0.00718443913104074
  - - 12
    - 0.00721816851753197
  - - 13
    - 0.0072543578351168345
  - - 14
    - 0.0072928932188134525
  - - 15
    - 0.007333653422047996
  - - 16
    - 0.007376510198141267
  - - 17
    - 0.0074213287038201944
  - - 18
    - 0.007467967923484664
  - - 19
    - 0.00751628111289476
  - - 20
    - 0.007566116260882442
  - - 21
    - 0.00761731656763491
  - - 22
    - 0.007669720938044833
  - - 23
    - 0.007723164488575151
  - - 24
    - 0.007777479066043686
  - - 25
    - 0.007832493776695263
  - - 26
    - 0.007888035523896691
  - - 27
    - 0.007943929552762808
  - - 28
    - 0.008
  - - 29
    - 0.008056070447237192
  - - 30
    - 0.008111964476103309
  - - 31
    - 0.008167506223304737
  - - 32
    - 0.008222520933956314
  - - 33
    - 0.00827683551142485
  - - 34
    - 0.008330279061955166
  - - 35
    - 0.00838268343236509
  - - 36
    - 0.008433883739117558
  - - 37
    - 0.00848371888710524
  - - 38
    - 0.008532032076515336
  - - 39
    - 0.008578671296179806
  - - 40
    - 0.008623489801858734
  - - 41
    - 0.008666346577952004
  - - 42
    - 0.008707106781186547
  - - 43
    - 0.008745642164883166
  - - 44
    - 0.00878183148246803
  - - 45
    - 0.00881556086895926
  - - 46
    - 0.008846724199228283
  - - 47
    - 0.008875223421908754
  - - 48
    - 0.008900968867902419
  - - 49
    - 0.008923879532511288
  - - 50
    - 0.008943883330308367
  - - 51
    - 0.0089609173219451
  - - 52
    - 0.008974927912181824
  - - 53
    - 0.008985871018518237
  - - 54
    - 0.008993712209893243
  - - 55
    - 0.008998426815017817
  - - 56
    - 0.009000000000000001
  - - 57
    - 0.008998426815017817
  - - 58
    - 0.008993712209893243
  - - 59
    - 0.008985871018518237
  - - 60
    - 0.008974927912181824
  - - 61
    - 0.0089609173219451
  - - 62
    - 0.008943883330308367
  - - 63
    - 0.008923879532511288
  - - 64
    - 0.008900968867902419
  - - 65
    - 0.008875223421908754
  - - 66
    - 0.008846724199228285
  - - 67
    - 0.00881556086895926
  - - 68
    - 0.008781831482468031
  - - 69
    - 0.008745642164883166
  - - 70
    - 0.008707106781186549
  - - 71
    - 0.008666346577952004
  - - 72
    - 0.008623489801858734
  - - 73
    - 0.008578671296179806
  - - 74
    - 0.008532032076515338
  - - 75
    - 0.008483718887105241
  - - 76
    - 0.008433883739117558
  - - 77
    - 0.00838268343236509
  - - 78
    - 0.008330279061955168
  - - 79
    - 0.00827683551142485
  - - 80
    - 0.008222520933956316
  - - 81
    - 0.008167506223304737
  - - 82
    - 0.008111964476103309
  - - 83
    - 0.008056070447237192
  - - 84
    - 0.008
  - - 85
    - 0.007943929552762808
  - - 86
    - 0.007888035523896693
  - - 87
    - 0.007832493776695263
  - - 88
    - 0.007777479066043686
  - - 89
    - 0.007723164488575151
  - - 90
    - 0.007669720938044833
  - - 91
    - 0.00761731656763491
  - - 92
    - 0.007566116260882442
  - - 93
    - 0.00751628111289476
  - - 94
    - 0.007467967923484664
  - - 95
    - 0.007421328703820195
  - - 96
    - 0.007376510198141267
  - - 97
    - 0.007333653422047996
  - - 98
    - 0.0072928932188134525
  - - 99
    - 0.0072543578351168345
  - - 100
    - 0.007218168517531971
  - - 101
    - 0.00718443913104074
  - - 102
    - 0.007153275800771716
  - - 103
    - 0.007124776578091247
  - - 104
    - 0.007099031132097582
  - - 105
    - 0.0070761204674887135
  - - 106
    - 0.007056116669691632
  - - 107
    - 0.007039082678054901
  - - 108
    - 0.007025072087818177
  - - 109
    - 0.0070141289814817645
  - - 110
    - 0.007006287790106758
  - - 111
    - 0.007001573184982184
  sample_noise: 0.0005
container_volumes:
- 1
order_generate_mode: fixed
ports:
  demand_port_001:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.25
    order_distribution:
      source:
        noise: 0.033533049344983426
        proportion: 0.33
      targets:
        supply_port_001:
          noise: 0.19263966991617276
          proportion: 1
  demand_port_002:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.25
    order_distribution:
      source:
        noise: 0.07994328709432799
        proportion: 0.67
      targets:
        supply_port_001:
          noise: 0.020281054537973634
          proportion: 0.2
        supply_port_002:
          noise: 0.013539697235951867
          proportion: 0.8
  supply_port_001:
    capacity: 1000000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.25
    order_distribution:
      source:
        noise: 0.0
        proportion: 0
  supply_port_002:
    capacity: 100000
    empty_return:
      buffer_ticks: 1
      noise: 1
    full_return:
      buffer_ticks: 1
      noise: 1
    initial_container_proportion: 0.25
    order_distribution:
      source:
        noise: 0.0
        proportion: 0
routes:
  route_001:
  - distance: 400
    port_name: supply_port_001
  - distance: 400
    port_name: demand_port_001
  route_002:
  - distance: 400
    port_name: supply_port_001
  - distance: 400
    port_name: supply_port_002
  - distance: 400
    port_name: demand_port_002
stop_number:
- 4
- 3
total_containers: 100000
vessels:
  rt1_vessel_001:
    capacity: 6000
    parking:
      duration: 2
      noise: 0
    route:
      initial_port_name: supply_port_001
      route_name: route_001
    sailing:
      noise: 0
      speed: 50
  rt1_vessel_002:
    capacity: 8000
    parking:
      duration: 2
      noise: 0
    route:
      initial_port_name: demand_port_001
      route_name: route_001
    sailing:
      noise: 0
      speed: 50
  rt2_vessel_001:
    capacity: 10000
    parking:
      duration: 2
      noise: 0
    route:
      initial_port_name: supply_port_001
      route_name: route_002
    sailing:
      noise: 0
      speed: 50
  rt2_vessel_002:
    capacity: 6000
    parking:
      duration: 2
      noise: 0
    route:
      initial_port_name: supply_port_002
      route_name: route_002
    sailing:
      noise: 0
      speed: 50
  rt2_vessel_003:
    capacity: 8000
    parking:
      duration: 2
      noise: 0
    route:
      initial_port_name: demand_port_002
      route_name: route_002
    sailing:
      noise: 0
      speed: 50
