seed: 1024

station:
  latitude: 32.72329226
  longitude: -117.0718922
  close_rtb: 960 # Unit: tick

interrupt_cycle: 10

order_transition:
  buffer_before_open_time: 30 # Unit: tick; how long it could be ready in advance
  buffer_after_open_time: 30  # Unit: tick; actual termination tick would be min(close + buffer, rtb)
  last_tick_for_order_processing: 960  # Unit: tick
  processing_time: 1  # Unit: tick
  processing_proportion_to_quantity: False  # If True, processing_time * order quantity to process

data_loader_config:
  data_loader_type: "history" # history, sample
  oncall_generator_type: "sample" # history, sample
  start_tick: 0
  end_tick: 1439
