# Initial buffer time budget.
BUFFER_TIME_BUDGET: 0
# The number of ticks to delay when agent decides not to assign VM.
DELAY_DURATION: 1

# Path of the vm table data.
VM_TABLE: "~/.maro/data/vm_scheduling/.build/azure.2019.336k/vmtable.bin"

# Path of the cpu readings file.
CPU_READINGS: "~/.maro/data/vm_scheduling/.build/azure.2019.336k/vm_cpu_readings-file-1-of-195.bin"

PROCESSED_DATA_URL: "https://marodatasource.blob.core.windows.net/vm-scheduling-azure/azure.2019.336k/azure.2019.336k.tar.gz"

# True means kill all VMs on the overload PM.
# False means only count these VMs as failed allocation, but not kill them.
KILL_ALL_VMS_IF_OVERLOAD: True

# Oversubscription configuration.
# Max CPU oversubscription rate.
MAX_CPU_OVERSUBSCRIPTION_RATE: 1.15
# Max memory oversubscription rate.
MAX_MEM_OVERSUBSCRIPTION_RATE: 1
# Max CPU utilization rate.
MAX_UTILIZATION_RATE: 1

# Price parameter of CPU cores
PRICE_PARAMETERS_CPU_CORES: 0.0698
# Price parameter of CPU cores
PRICE_PARAMETERS_MEMORY: 0.0078
# Unit price of Energy
UNIT_ENERGY_PRICE: 0.07
# POWER USAGE EFFICIENCY, PUE=(Total Facility Power)/(IT Equipment Power)
POWER_USAGE_EFFICIENCY: 1.7

components:
  pm:
    - pm_type: 0
      cpu: 32
      memory: 128
      power_curve:
        calibration_parameter: 1.4
        busy_power: 185
        idle_power: 120
    - pm_type: 1
      cpu: 16
      memory: 112
      power_curve:
        calibration_parameter: 1.4
        busy_power: 10
        idle_power: 1
  rack:
    - type: 'a'
      pm:
        - pm_type: 0
          pm_amount: 10
    - type: 'b'
      pm:
        - pm_type: 1
          pm_amount: 10
  cluster:
    - type: 'JP1'         # 100 pm/cluster
      rack:
        - rack_type: 'a'
          rack_amount: 10
    - type: 'JP2'         # 100 pm/cluster
      rack:
        - rack_type: 'b'
          rack_amount: 10
    - type: 'JP3'         # 100 pm/cluster
      rack:
        - rack_type: 'a'
          rack_amount: 5
        - rack_type: 'b'
          rack_amount: 5

architecture:
  region:
    - name: 'APAC'
      zone:
        - name: 'asia-northeast1'
          data_center:
            - name: 'Japan'
              cluster:
                - type: 'JP1'
                  cluster_amount: 2
                - type: 'JP2'
                  cluster_amount: 4
                - type: 'JP3'
                  cluster_amount: 2
