mode: process
name: MyJobName # str: name of the training job

components: # component config
  actor:
    num: 5 # int: number of this component
    command: "python /target/path/run_actor.py" # str: command to be executed
  learner:
    num: 1
    command: "python /target/path/run_learner.py"
