# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job_name: cim-dqn 
scenario: cim
mode: sync
num_episodes: 5
eval_schedule: 5
num_steps: -1
max_lag: 0
log_env_summary: true
sync:
  rollout_group: rollout
  rollout_mode: multi-node # single-process, multi-process, multi-node
  num_rollout_workers: 6
  min_finished_workers: 4
  # max_extra_recv_tries: 3
  extra_recv_timeout: 100
async:
  group: async
  num_actors: 3
policy_manager:
  train_group: policy-manager
  train_mode: multi-node # single-process, multi-process, multi-node
  num_trainers: 2
redis:
  host: maro-redis
  port: 6379