experiment_name: test

env:
  scenario: vm_scheduling
  topology: azure.2019.10k
  start_tick: 0
  durations: 8638
  resolution: 1
  seed: 128

ilp:
  solver: GLPK  # GLPK, GUROBI
  plan_window_size: 3
  # apply_buffer_size: 5
  performance:
    core_safety_remaining_ratio: 0
    mem_safety_remaining_ratio: 0
  objective:
    successful_allocation_decay: 0.99
    allocation_multiple_core_num: false
  log:
    dump_all_solution: false
    dump_infeasible_solution: true
    stdout_solver_message: true
