# This is a basic workflow to help you get started with Actions

name: deploy_docker_image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#   push:
#     tags:
#     - "v*.*.*"
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'package version'     
        required: true
        default: '0.1.1a0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
        uses: docker/build-push-action@v1.1.1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: arthursjiang/maro
          # Docker repository to tag the image with
          repository: latest
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: citi-bike, inventory-management, operations-research, reinforcement-learning, resource-optimization, simulator
          # Automatically tags the built image with the git reference as per the readme
          # Path to the build context
          path: .
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: docker_files/cpu.play.df
          # Sets the target stage to build
          target: maro/playground:cpu
          # Whether to push the image
          push: true
